package ch.mrs.matrix;

public enum MatrixFeature {
	INDIVIDUAL_ORIGIN,
	INDIVIDUAL_SEX,
	INDIVIDUAL_AGE,
	INDIVIDUAL_RELIGION,
	INDIVIDUAL_FAMILY_SIZE,
	
	CITY_POPULATION,
	CITY_BORN,
	CITY_DIED,
	CITY_MARIAGE,
	CITY_DIVORCE,
	CITY_STUDENTS,
	
	WORKPLACES_SECTORS,
	WORKPLACES_SIZE,
	WORKERS_SECTOR,
	WORKERS_GASTRO,
	
	BUILDINGS_USAGE,
	BUILDINGS_VACANT_HOMES,
	
	ZONES_USAGE,

	TRANSPORT_CONNECTIVITY,
}
